# Generated by Django 3.2.12 on 2025-01-30 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0002_auto_20250126_1839'),
        ('volunteers', '0002_auto_20250130_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteeractivity',
            name='volunteers_registered',
        ),
        migrations.CreateModel(
            name='VolunteerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteeractivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_center.user')),
            ],
            options={
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
