# Generated by Django 3.2.12 on 2025-01-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('Password', models.CharField(max_length=100, verbose_name='密码')),
                ('Phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('Email', models.EmailField(blank=True, default='1', max_length=254, unique=True, verbose_name='邮箱')),
                ('Head', models.ImageField(blank=True, default='/media/images/山湖.jpg', null=True, upload_to='images')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
